// scripts/css-analysis/report.mjs
// Stage 4: render the four committed reports from the cache.
//   docs/css-audit/inventory.csv     — sortable per-row inventory
//   docs/css-audit/clusters.md       — exact + fuzzy + collisions
//   docs/css-audit/literal-map.md    — what tokens each raw value should map to
//   docs/css-audit/jsx-refs.md       — per-class JSX usage hint

import { loadConfig, readCache, writeReport } from "./lib.mjs";

const cfg = loadConfig();
const canonical = readCache("canonicalized");
const clusters = readCache("clusters");

// ---------- inventory.csv ----------
//
// Wide CSV: one row per rule. Columns picked so a spreadsheet sort
// can group by block, property_set, decl_hash, etc.

function csvEscape(v) {
  if (v === null || v === undefined) return "";
  const s = String(v);
  if (s.includes(",") || s.includes('"') || s.includes("\n")) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

const csvHeader = [
  "id",
  "file",
  "line",
  "selector",
  "primary_class",
  "block",
  "property_set",
  "jsx_refs",
  "decl_hash_normalized",
  "decl_hash_raw",
  "tokens_used",
  "remaining_raw_values",
  "canonical_signature",
];

const csvLines = [csvHeader.join(",")];
for (const row of canonical) {
  csvLines.push([
    row.id,
    row.file,
    row.line,
    row.selector,
    row.primary_class,
    row.block,
    row.property_set,
    row.jsx_refs,
    row.decl_hash_normalized,
    row.decl_hash_raw,
    row.tokens_used.join(" "),
    Object.entries(row.remaining_raw_values).map(([p, v]) => `${p}=${v}`).join(" "),
    row.canonical_signature,
  ].map(csvEscape).join(","));
}
writeReport("inventory.csv", csvLines.join("\n") + "\n");

// ---------- clusters.md ----------

const md = [];
md.push("# CSS audit — clusters");
md.push("");
md.push(`_Generated by \`npm run css:audit\` at ${clusters.generated_at}._`);
md.push("");
md.push(`Fuzzy tolerance: **${clusters.tolerance_pct}%** (Algorithm 2 only — canonical signatures stay exact per plan §3.2).`);
md.push(`Primitive threshold (min cluster size): **${clusters.primitive_threshold}**.`);
md.push("");
md.push("---");
md.push("");

md.push("## §1 Exact-duplicate clusters");
md.push("");
md.push("Rule-sets that produce literally identical CSS after token resolution. These are the strongest primitive candidates.");
md.push("");
md.push("");
md.push("Two counts per cluster:");
md.push("- **selector_occurrences**: total inventory rows in the cluster (semantic spread / rename blast radius).");
md.push("- **sites**: unique `file:line` count (actual CSS edit-site count).");
md.push("");
md.push("`.a, .b, .c { ... }` is 3 selector occurrences but 1 site.");
md.push("");

if (clusters.exact_clusters.length === 0) {
  md.push("_No exact duplicates above threshold._");
} else {
  for (const c of clusters.exact_clusters) {
    md.push(`### ${c.selector_occurrences} selectors / ${c.site_count} sites — \`${c.property_set || "(empty)"}\``);
    md.push("");
    md.push("```css");
    const declStrs = c.signature.split(";").filter(Boolean);
    md.push("{");
    for (const d of declStrs) md.push(`  ${d};`);
    md.push("}");
    md.push("```");
    md.push("");
    md.push("Members:");
    for (const id of c.members) md.push(`- \`${id}\``);
    md.push("");
  }
}

md.push("---");
md.push("");
md.push("## §2 Fuzzy / near-duplicate clusters");
md.push("");
md.push(`Same property set, ≥80% values identical, the rest within ${clusters.tolerance_pct}% numerically. Candidates for collapsing to one token.`);
md.push("");
if (clusters.fuzzy_clusters.length === 0) {
  md.push("_No fuzzy clusters above threshold._");
} else {
  for (const c of clusters.fuzzy_clusters) {
    md.push(`### ${c.selector_occurrences} selectors / ${c.site_count} sites / ${c.distinct_normalized_signatures} distinct sigs — \`${c.property_set}\``);
    md.push("");
    for (const m of c.members) md.push(`- \`${m.id}\`  \`${m.canonical_signature}\``);
    md.push("");
  }
}

md.push("---");
md.push("");
md.push("## §3 Cross-file collisions / shared-class candidates");
md.push("");
md.push("Same primary class name in multiple files. If the declarations match: extract a primitive. If they don't: rename one (BEM block prefix).");
md.push("");
if (clusters.collisions.length === 0) {
  md.push("_No cross-file class duplicates._");
} else {
  md.push("| Class | Files | Distinct sigs | Verdict |");
  md.push("| --- | --- | ---: | --- |");
  for (const c of clusters.collisions) {
    md.push(`| \`.${c.class_name}\` | ${c.file_count} | ${c.distinct_signatures} | ${c.verdict} |`);
  }
  md.push("");
  md.push("### Detail");
  md.push("");
  for (const c of clusters.collisions) {
    md.push(`#### \`.${c.class_name}\` (${c.verdict})`);
    for (const m of c.members) md.push(`- \`${m.id}\``);
    md.push("");
  }
}

writeReport("clusters.md", md.join("\n") + "\n");

// ---------- literal-map.md ----------

const lm = [];
lm.push("# CSS audit — literal → token map");
lm.push("");
lm.push(`_Generated by \`npm run css:audit\` at ${clusters.generated_at}._`);
lm.push("");
lm.push("Per-property tables of every raw value still present in the inventory. The right-hand column is the token the config maps to, or — if unknown — a note that this value needs a token decision (sometimes a new token, sometimes a closest-match).");
lm.push("");

function bucketTable(title, freqs, tokenMap) {
  lm.push(`## ${title}`);
  lm.push("");
  if (freqs.length === 0) {
    lm.push("_No remaining raw literals in this category._");
    lm.push("");
    return;
  }
  lm.push("| Raw value | Count | Configured token | Notes |");
  lm.push("| --- | ---: | --- | --- |");
  for (const { value, count } of freqs) {
    const tok = tokenMap[value] || "";
    const note = tok ? "exact match" : "needs decision";
    lm.push(`| \`${value}\` | ${count} | ${tok ? "`" + tok + "`" : ""} | ${note} |`);
  }
  lm.push("");
}

bucketTable("Colors", clusters.property_frequency.colors, cfg.token_lookup.colors);
bucketTable("Font sizes", clusters.property_frequency.font_sizes, cfg.token_lookup.font_sizes);
bucketTable("Spacing (padding / margin / gap)", clusters.property_frequency.spacing, cfg.token_lookup.spacing);
bucketTable("Border radius", clusters.property_frequency.radii, cfg.token_lookup.radii);

writeReport("literal-map.md", lm.join("\n") + "\n");

// ---------- jsx-refs.md ----------

const jx = [];
jx.push("# CSS audit — JSX className usage (lower-bound hint)");
jx.push("");
jx.push("_This is a **lower-bound** usage signal, not an exact count. The regex only catches static class tokens inside `className=\"...\"`. Dynamic composition like `` className={`foo-${variant}`} ``, computed strings, and `.js`/`.ts`/`.tsx` files are not searched. Treat as low-blast / high-blast triage._");
jx.push("");
jx.push("| Class | jsx_refs (≥) | File | Line |");
jx.push("| --- | ---: | --- | ---: |");

// Sort by jsx_refs descending so high-blast classes float to the top.
const sorted = canonical.slice().sort((a, b) => b.jsx_refs - a.jsx_refs);
for (const r of sorted) {
  jx.push(`| \`.${r.primary_class}\` | ${r.jsx_refs} | \`${r.file}\` | ${r.line} |`);
}

writeReport("jsx-refs.md", jx.join("\n") + "\n");

console.log(`[report] wrote inventory.csv / clusters.md / literal-map.md / jsx-refs.md to ${cfg.output_dir}/`);
